version: "3.9"

services:
  php:
      hostname: switchscreenshots
      container_name: sys-screenshot-plugins
      image: sys-screenshot-plugins
      restart: always
      volumes:
        - ${pictures_path}/pictures:/var/www/html/pictures/
        - ${config_path}/config/config.php:/var/www/html/config.php
        - ${config_path}/config/log.log:/var/www/html/log.log
      # remove the # to open the port 80
      # ports:
        # - "80:80" 
      build:
        context: .
        dockerfile: Dockerfile
        target: base
# remove all under here if you dont use a network
networks:
  default:
    external:
      name: proxy-manager_default # change this to your desired network
