name: remote ssh command
on: [push]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: removing old files from server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/${{ secrets.USERNAME }}/github_actions 
          rm * -rf
    - name: copying files to server
      uses: srueda99/scp-action@v12
      with:
          port: 22
          host: ${{ secrets.HOST }}
          destination: "/home/${{ secrets.USERNAME }}/github_actions"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
    - name: executing some commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/${{ secrets.USERNAME }}/github_actions 
          touch it_works 
          rm -f key